# Stage 1: Build
FROM node:22-slim AS builder

# Fix for the "Reached heap limit" error. 
# 4096 (4GB) is usually the sweet spot for GitHub Action runners.
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV CI=true
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Install build tools for native modules (e.g., better-sqlite3, argon2)
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
RUN corepack enable

WORKDIR /app

# Install dependencies (utilizing Docker layer caching)
COPY pnpm-lock.yaml package.json ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

# Copy source and build
COPY . .
RUN npx prisma generate
RUN pnpm run build

# Clean up build-time node_modules to ensure Stage 3 stays small
RUN rm -rf .output/server/node_modules

# Stage 2: Production Dependencies
# This stage isolates only the modules needed to RUN the server
FROM node:22-slim AS prod-deps
RUN apt-get update && apt-get install -y openssl python3 make g++ && rm -rf /var/lib/apt/lists/*
WORKDIR /app

# Copy the server package.json generated by Nitro/Nuxt
COPY --from=builder /app/.output/server/package.json ./package.json

# Install ONLY production dependencies
# --legacy-peer-deps handles the version mismatch between better-auth and Prisma 7
RUN npm install --omit=dev --legacy-peer-deps

# Stage 3: Final Production Image
FROM node:22-slim

# Required for Prisma/Database engine to run on Debian-slim
RUN apt-get update && apt-get install -y openssl && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV NODE_ENV=production

# Copy the built Nitro server
COPY --from=builder /app/.output ./.output

# Copy the lean production node_modules into the Nitro server directory
COPY --from=prod-deps /app/node_modules ./.output/server/node_modules

# Copy Prisma schema and generated client 
# (Nuxt/Nitro usually bundles the client, but keeping these ensures 
# runtime migrations or manual scripts work)
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

# Start the Nitro server
CMD ["node", ".output/server/index.mjs"]
